<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\Pjax;

use app\views\colaboradores\colaboradoresHelper;

use kartik\grid\GridView;
/* @var $this yii\web\View */
/* @var $searchModel app\models\searches\ColaboradoresSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$gridColumns = colaboradoresHelper::gridColumns(colaboradoresHelper::input_id_ccusto($id_ccusto));
$nome_ccusto = colaboradoresHelper::nome_ccusto($id_ccusto);

$this->title = Yii::t('app', 'Colaboradores');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="colaboradores-terminus">

<?=GridView::widget([
  'dataProvider'=>$dataProvider,
  'autoXlFormat'=>true,
  'columns'=>$gridColumns,
  'pjax'=>true,
  'showPageSummary'=>false,
  'exportConfig' => [
    GridView::PDF => [
        'filename' => Yii::t('kvgrid', 'Colaboradores - '.$nome_ccusto),
        'config' => [
            'mode' => 'c',
            'format' => 'A4-L',
            'destination' => 'D',
            'marginTop' => 20,
            'marginBottom' => 20,
            'cssInline' => '.kv-wrap{padding:20px;}' .
                '.kv-align-center{text-align:center;}' .
                '.kv-align-left{text-align:left;}' .
                '.kv-align-right{text-align:right;}' .
                '.kv-align-top{vertical-align:top!important;}' .
                '.kv-align-bottom{vertical-align:bottom!important;}' .
                '.kv-align-middle{vertical-align:middle!important;}' .
                '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
            'methods' => [
                'SetHeader' => [
                    ['odd' => '', 'even' => '']
                ],
                'SetFooter' => [
                    ['odd' => '', 'even' => '']
                ],
            ],
            'options' => [
                'title' => 'Colaboradores - '.$nome_ccusto,
                'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
                'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
            ],
            'contentBefore'=>'',
            'contentAfter'=>''
        ]
    ],
    GridView::EXCEL => [
      'filename' => Yii::t('kvgrid', 'Colaboradores - '.$nome_ccusto),
    ],
  ],
  'export'=>[
    'label'=>'exportar',
      'fontAwesome'=>false,
      'header'=>'',
      'showConfirmAlert'=>false,
      'target'=>GridView::TARGET_BLANK,
  ],
  'toggleDataOptions' => [
      'all' => [
          'icon' => 'resize-full',
          'label' => Yii::t('kvgrid', 'TUDO'),
          'class' => 'btn btn-default',
          'title' => 'Mostrar todos os resultados'
      ],
      'page' => [
          'icon' => 'resize-small',
          'label' => Yii::t('kvgrid', 'Página'),
          'class' => 'btn btn-default',
          'title' => 'Mostrar apenas a primeira página'
      ],
  ],
  'panel' => [
  'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-list-alt"></i> Colaboradores - '.
    $nome_ccusto
    .'</h3>',
    'type'=>'danger',
    'footer'=>false
  ],
]);?>
</div>
